# Generated by Django 4.2.13 on 2024-06-27 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="menu_images/"
            ),
            preserve_default=False,
        ),
    ]
