# Generated by Django 4.2.13 on 2024-06-29 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_purchasehistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasehistory",
            old_name="created_at",
            new_name="date_purchased",
        ),
        migrations.RemoveField(
            model_name="purchasehistory",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="purchase_images/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="price",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
