# Generated by Django 4.2.13 on 2024-06-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_rename_created_at_purchasehistory_date_purchased_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasehistory",
            name="date_purchased",
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="image",
            field=models.URLField(),
        ),
    ]
